CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('income', 'expense')),
    date DATE NOT NULL,
    category_id INTEGER NOT NULL REFERENCES categories(id),

    -- filled in only if this row was generated by an installment purchase
    installment_purchase_id INTEGER REFERENCES installment_purchases(id),
    installment_number INTEGER,

    -- filled in only if this row was generated by a consolidated debt payment
    debt_payment_id INTEGER REFERENCES debt_payments(id),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);